- name: Instalar paquetes necesarios para LAMP (Nginx, PHP-FPM)
  apt:
    name:
      - nginx
      - php-fpm
      - php-mysql
      - php-mbstring
      - git
    state: present
    update_cache: yes

- name: Configuración de virtualhost
  template: 
    src: etc/nginx/vhost.j2
    dest: /etc/nginx/sites-available/{{item["name"]}}
    owner: root
    group: root
  with_items:
    - "{{virtualhosts}}"

- name: Crear DocumentRoot si no existe
  ansible.builtin.file:
    path: /{{item["datos"]["documentroot"]}}
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  with_items:
    - "{{virtualhosts}}"


- name: Activación de los VirtualHost
  file:
    src: /etc/nginx/sites-available/{{item["name"]}}
    dest: /etc/nginx/sites-enabled/{{item["name"]}}
    state: link
  with_items:
    - "{{virtualhosts}}"
  notify: restart nginx


- name: Copiar aplicación Guestbook
  ansible.builtin.copy:
    src: app/
    dest: "/{{ base_web_path }}/"
    owner: www-data
    group: www-data
    mode: '0644'
    directory_mode: '0755'
  
- name: Crear fichero de configuración config.php dentro de la aplicación
  ansible.builtin.template:
    src: config.php.j2
    dest: "/{{ base_web_path }}/config.php"
    owner: www-data
    group: www-data

- name: Configurar PHP-FPM para escuchar en todas las interfaces
  ansible.builtin.lineinfile:
    path: /etc/php/8.4/fpm/pool.d/www.conf
    regexp: 'listen = /run/php/'
    line: 'listen = 9000'
    state: present
  notify: restart php-fpm
